apiVersion: v1
kind: Service
metadata:
  name: {{ include "ddb-api-v3.apiServiceName" . }}
  labels:
    {{- include "ddb-api-v3.labels" . | nindent 4 }}
    app.kubernetes.io/component: api-service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
  selector:
    {{- include "ddb-api-v3.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api-service
