{{- if .Values.apiService.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "ddb-api-v3.apiServiceName" . }}
  labels:
    {{- include "ddb-api-v3.labels" . | nindent 4 }}
    app.kubernetes.io/component: api-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "ddb-api-v3.apiServiceName" . }}
  minReplicas: {{ .Values.apiService.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.apiService.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.apiService.autoscaling.targetCPUUtilizationPercentage }}
---
{{- end }}
{{- if .Values.gateway.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "ddb-api-v3.gatewayName" . }}
  labels:
    {{- include "ddb-api-v3.labels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "ddb-api-v3.gatewayName" . }}
  minReplicas: {{ .Values.gateway.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.gateway.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.gateway.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}

