apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ required "redis.serviceAccount.name is required" .Values.redis.serviceAccount.name }}
  labels:
    {{- include "ddb-api-v3.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
automountServiceAccountToken: false
